import { chromium } from "playwright";
const browser = await chromium.launch({ headless: true, args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 1280, height: 860 } });
page.on("pageerror", (e) => console.log("ERR", e.message));
page.on("console", (m) => { if (m.type() === "error") console.log("C", m.text()); });
await page.goto("http://127.0.0.1:8080/login", { waitUntil: "domcontentloaded" });
// last created user unknown — create another and post, then reload
const email = `bd.${Date.now()}@supercleads.com`;
await page.getByRole("button", { name: /create an account/i }).click();
await page.getByPlaceholder("Jaydan").fill("Marcus Cole");
await page.locator('input[type="email"]').fill(email);
await page.locator('input[type="password"]').fill("FloorBoard4995");
await page.getByRole("button", { name: /create floor account/i }).click();
await page.getByRole("heading", { name: /the board/i }).waitFor({ timeout: 25000 });
console.log("people before", await page.locator("article header").allInnerTexts());
await page.getByRole("button", { name: /draw an x/i }).first().click();
await page.locator("canvas").waitFor();
const box = await page.locator("canvas").boundingBox();
await page.mouse.move(box.x + 50, box.y + 40);
await page.mouse.down();
await page.mouse.move(box.x + box.width - 50, box.y + box.height - 40, { steps: 16 });
await page.mouse.up();
await page.mouse.move(box.x + box.width - 50, box.y + 40);
await page.mouse.down();
await page.mouse.move(box.x + 50, box.y + box.height - 40, { steps: 16 });
await page.mouse.up();
await page.waitForTimeout(200);
const hang = page.getByRole("button", { name: /hang the x/i });
console.log("hang disabled", await hang.isDisabled());
await hang.click();
await page.waitForTimeout(2000);
console.log("url", page.url());
console.log("headers", await page.locator("article header").allInnerTexts());
console.log("body snippet", (await page.locator("body").innerText()).slice(0, 900));
await page.screenshot({ path: "/workspace/screenshots/whiteboard-debug.png" });
await browser.close();
