/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PayRouteImport } from './routes/pay'
import { Route as AuthPopupRouteImport } from './routes/auth/popup'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as CrmCustomerIdRouteImport } from './routes/crm.$customerId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPopupRoute = AuthPopupRouteImport.update({
  id: '/auth/popup',
  path: '/auth/popup',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmCustomerIdRoute = CrmCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CrmRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/crm': typeof CrmRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/desk': typeof DeskRoute
  '/follow-ups': typeof FollowUpsRoute
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/auth/popup': typeof AuthPopupRoute
  '/crm/$customerId': typeof CrmCustomerIdRoute
  '/crm/': typeof CrmIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/desk': typeof DeskRoute
  '/follow-ups': typeof FollowUpsRoute
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/auth/popup': typeof AuthPopupRoute
  '/crm/$customerId': typeof CrmCustomerIdRoute
  '/crm': typeof CrmIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/crm': typeof CrmRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/desk': typeof DeskRoute
  '/follow-ups': typeof FollowUpsRoute
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/auth/popup': typeof AuthPopupRoute
  '/crm/$customerId': typeof CrmCustomerIdRoute
  '/crm/': typeof CrmIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/crm'
    | '/dashboard'
    | '/desk'
    | '/follow-ups'
    | '/login'
    | '/pay'
    | '/auth/popup'
    | '/crm/$customerId'
    | '/crm/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/desk'
    | '/follow-ups'
    | '/login'
    | '/pay'
    | '/auth/popup'
    | '/crm/$customerId'
    | '/crm'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/crm'
    | '/dashboard'
    | '/desk'
    | '/follow-ups'
    | '/login'
    | '/pay'
    | '/auth/popup'
    | '/crm/$customerId'
    | '/crm/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CrmRoute: typeof CrmRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DeskRoute: typeof DeskRoute
  FollowUpsRoute: typeof FollowUpsRoute
  LoginRoute: typeof LoginRoute
  PayRoute: typeof PayRoute
  AuthPopupRoute: typeof AuthPopupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/popup': {
      id: '/auth/popup'
      path: '/auth/popup'
      fullPath: '/auth/popup'
      preLoaderRoute: typeof AuthPopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/$customerId': {
      id: '/crm/$customerId'
      path: '/$customerId'
      fullPath: '/crm/$customerId'
      preLoaderRoute: typeof CrmCustomerIdRouteImport
      parentRoute: typeof CrmRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CrmRouteChildren {
  CrmCustomerIdRoute: typeof CrmCustomerIdRoute
  CrmIndexRoute: typeof CrmIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmCustomerIdRoute: CrmCustomerIdRoute,
  CrmIndexRoute: CrmIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CrmRoute: CrmRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DeskRoute: DeskRoute,
  FollowUpsRoute: FollowUpsRoute,
  LoginRoute: LoginRoute,
  PayRoute: PayRoute,
  AuthPopupRoute: AuthPopupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
